require "mkmf"

dir_config('flite')

unless have_library('flite', 'flite_init')
  saved_libs = $libs
  puts "checkign for audio libraries depended by flite ..."
  unless [['asound'], ['winmm'], ['pulse-simple', 'pulse']].any? do |libs|
      $libs = saved_libs
      libs.all? { |lib| have_library(lib) } && have_library('flite', 'flite_init')
    end
    raise "Failed to find flite libraries."
  end
end

have_func('flite_voice_load')
have_func('flite_add_lang')
have_struct_member('cst_audio_streaming_info', 'utt', 'flite/cst_audio.h')

langs = with_config('langs', 'eng,indic,grapheme')

langs.split(',').each do |lang|
  lib = if lang == 'eng'
          ['flite_usenglish', 'usenglish_init',
           'flite_cmulex', 'cmu_lex_init']
        else
          ["flite_cmu_#{lang}_lang", "cmu_#{lang}_lang_init",
           "flite_cmu_#{lang}_lex", "cmu_#{lang}_lex_init"]
        end
  if have_library(lib[0], lib[1]) and have_library(lib[2], lib[3])
    $defs << "-DHAVE_LANG_#{lang.upcase}"
  end
end

builtin_voices = {
  'kal'      => ['cmu_us_kal',   'cmu_us_kal_diphone'],
  'awb_time' => ['cmu_time_awb', 'cmu_time_awb_ldom'],
  'kal16'    => ['cmu_us_kal16', 'cmu_us_kal16_diphone'],
  'awb'      => ['cmu_us_awb',   'cmu_us_awb_cg'],
  'rms'      => ['cmu_us_rms',   'cmu_us_rms_cg'],
  'slt'      => ['cmu_us_slt',   'cmu_us_slt_cg'],
}

voices = with_config('voices', 'kal,awb_time,kal16,awb,rms,slt')

voices = voices.split(',').inject([]) do |memo, name|
  v = builtin_voices[name]
  if v
    puts "checking for voice #{name}... "
    if have_library("flite_#{v[0]}", "register_#{v[0]}")
      memo << [name, *v]
    end
  else
    puts "warning: #{name} is not a builtin voice."
  end
  memo
end

File.open('rbflite_builtin_voice_list.c', 'w') do |f|
  f.write <<EOS
/*
 * This file is automatically generated by extconf.rb.
 * Don't edit this.
 */
#include "rbflite.h"

EOS
  voices.each do |v|
    f.puts "cst_voice *register_#{v[1]}(const char *voxdir);"
  end
  f.puts ""
  voices.each do |v|
    f.puts "extern cst_voice *#{v[2]};"
  end
  f.write <<EOS

const rbflite_builtin_voice_t rbflite_builtin_voice_list[] = {
EOS
  voices.each do |v|
    f.puts(%Q[    {"#{v[0]}", register_#{v[1]}, &#{v[2]}},])
  end
  f.write <<EOS
    {NULL, NULL, NULL},
};
EOS
end

RUBY_VERSION =~ /(\d+).(\d+)/
$defs << "-DInit_flite=Init_flite_#{$1}#{$2}0"
create_makefile("flite_#{$1}#{$2}0")
